version: "3.6"
services:
  tor-node:
    image: osminogin/tor-simple
    restart: always
    links:
      - lnbits:myservice
    volumes:
      - ./torrc.sample:/etc/tor/torrc:ro
      # would be nice to mount under /var/lib/tor/hidden_service but
      # it fails for too permisive mode on the directory
      - tor_hidden_service:/var/lib/tor/
  
  lnbits:
    image: 'my-lnbits'
    build: .
    restart: always
    environment:
      PYTHONBUFFERED: 1
    # enables lnbits localy
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env:ro
      # # if you are using REST or gRPC API, mount the tls.cert or
      # # macaroon files here -- NOTE: requires absolute path without
      # # quotations (") in .env file
      # - ${LND_REST_CERT}:${LND_REST_CERT}:ro
      # - ${LND_REST_MACAROON}:${LND_REST_MACAROON}:ro
      # - ${LND_GRPC_CERT}:${LND_GRPC_CERT}:ro
      # - ${LND_GRPC_MACAROON}:${LND_GRPC_MACAROON}:ro
      # # Volume for SQLite data (instead of postgres -- not recommended).
      # - sqlite_data:/app/lnbits/data/

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER?}
      POSTGRES_PASSWORD: ${DB_PASSWORD?}
      POSTGRESS_DB: ${DB_NAME?}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  tor_hidden_service:
  # sqlite_data:
  db_data:
