# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lnbits.wallets.boltz_grpc_files.boltzrpc_pb2 as boltzrpc__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BoltzStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/boltzrpc.Boltz/GetInfo',
                request_serializer=boltzrpc__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetInfoResponse.FromString,
                )
        self.GetServiceInfo = channel.unary_unary(
                '/boltzrpc.Boltz/GetServiceInfo',
                request_serializer=boltzrpc__pb2.GetServiceInfoRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetServiceInfoResponse.FromString,
                )
        self.GetSubmarinePair = channel.unary_unary(
                '/boltzrpc.Boltz/GetSubmarinePair',
                request_serializer=boltzrpc__pb2.Pair.SerializeToString,
                response_deserializer=boltzrpc__pb2.SubmarinePair.FromString,
                )
        self.GetReversePair = channel.unary_unary(
                '/boltzrpc.Boltz/GetReversePair',
                request_serializer=boltzrpc__pb2.Pair.SerializeToString,
                response_deserializer=boltzrpc__pb2.ReversePair.FromString,
                )
        self.GetPairs = channel.unary_unary(
                '/boltzrpc.Boltz/GetPairs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetPairsResponse.FromString,
                )
        self.ListSwaps = channel.unary_unary(
                '/boltzrpc.Boltz/ListSwaps',
                request_serializer=boltzrpc__pb2.ListSwapsRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.ListSwapsResponse.FromString,
                )
        self.RefundSwap = channel.unary_unary(
                '/boltzrpc.Boltz/RefundSwap',
                request_serializer=boltzrpc__pb2.RefundSwapRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetSwapInfoResponse.FromString,
                )
        self.GetSwapInfo = channel.unary_unary(
                '/boltzrpc.Boltz/GetSwapInfo',
                request_serializer=boltzrpc__pb2.GetSwapInfoRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetSwapInfoResponse.FromString,
                )
        self.GetSwapInfoStream = channel.unary_stream(
                '/boltzrpc.Boltz/GetSwapInfoStream',
                request_serializer=boltzrpc__pb2.GetSwapInfoRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetSwapInfoResponse.FromString,
                )
        self.Deposit = channel.unary_unary(
                '/boltzrpc.Boltz/Deposit',
                request_serializer=boltzrpc__pb2.DepositRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.DepositResponse.FromString,
                )
        self.CreateSwap = channel.unary_unary(
                '/boltzrpc.Boltz/CreateSwap',
                request_serializer=boltzrpc__pb2.CreateSwapRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.CreateSwapResponse.FromString,
                )
        self.CreateChannel = channel.unary_unary(
                '/boltzrpc.Boltz/CreateChannel',
                request_serializer=boltzrpc__pb2.CreateChannelRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.CreateSwapResponse.FromString,
                )
        self.CreateReverseSwap = channel.unary_unary(
                '/boltzrpc.Boltz/CreateReverseSwap',
                request_serializer=boltzrpc__pb2.CreateReverseSwapRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.CreateReverseSwapResponse.FromString,
                )
        self.CreateWallet = channel.unary_unary(
                '/boltzrpc.Boltz/CreateWallet',
                request_serializer=boltzrpc__pb2.CreateWalletRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.WalletCredentials.FromString,
                )
        self.ImportWallet = channel.unary_unary(
                '/boltzrpc.Boltz/ImportWallet',
                request_serializer=boltzrpc__pb2.ImportWalletRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.Wallet.FromString,
                )
        self.SetSubaccount = channel.unary_unary(
                '/boltzrpc.Boltz/SetSubaccount',
                request_serializer=boltzrpc__pb2.SetSubaccountRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.Subaccount.FromString,
                )
        self.GetSubaccounts = channel.unary_unary(
                '/boltzrpc.Boltz/GetSubaccounts',
                request_serializer=boltzrpc__pb2.WalletInfo.SerializeToString,
                response_deserializer=boltzrpc__pb2.GetSubaccountsResponse.FromString,
                )
        self.GetWallets = channel.unary_unary(
                '/boltzrpc.Boltz/GetWallets',
                request_serializer=boltzrpc__pb2.GetWalletsRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.Wallets.FromString,
                )
        self.GetWallet = channel.unary_unary(
                '/boltzrpc.Boltz/GetWallet',
                request_serializer=boltzrpc__pb2.GetWalletRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.Wallet.FromString,
                )
        self.GetWalletCredentials = channel.unary_unary(
                '/boltzrpc.Boltz/GetWalletCredentials',
                request_serializer=boltzrpc__pb2.GetWalletCredentialsRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.WalletCredentials.FromString,
                )
        self.RemoveWallet = channel.unary_unary(
                '/boltzrpc.Boltz/RemoveWallet',
                request_serializer=boltzrpc__pb2.RemoveWalletRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.RemoveWalletResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/boltzrpc.Boltz/Stop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Unlock = channel.unary_unary(
                '/boltzrpc.Boltz/Unlock',
                request_serializer=boltzrpc__pb2.UnlockRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.VerifyWalletPassword = channel.unary_unary(
                '/boltzrpc.Boltz/VerifyWalletPassword',
                request_serializer=boltzrpc__pb2.VerifyWalletPasswordRequest.SerializeToString,
                response_deserializer=boltzrpc__pb2.VerifyWalletPasswordResponse.FromString,
                )
        self.ChangeWalletPassword = channel.unary_unary(
                '/boltzrpc.Boltz/ChangeWalletPassword',
                request_serializer=boltzrpc__pb2.ChangeWalletPasswordRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class BoltzServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """
        Gets general information about the daemon like the chain of the lightning node it is connected to
        and the IDs of pending swaps.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceInfo(self, request, context):
        """
        Fetches the latest limits and fees from the Boltz backend API it is connected to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubmarinePair(self, request, context):
        """
        Fetches information about a specific pair for a submarine swap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReversePair(self, request, context):
        """
        Fetches information about a specific pair for a reverse swap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPairs(self, request, context):
        """
        Fetches all available pairs for submarine and reverse swaps.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSwaps(self, request, context):
        """
        Returns a list of all swaps, reverse swaps and channel creations in the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundSwap(self, request, context):
        """
        Refund a failed swap manually.
        This is only required when no refund address has been set or the daemon has no wallet for the currency.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSwapInfo(self, request, context):
        """
        Gets all available information about a swap from the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSwapInfoStream(self, request, context):
        """
        Returns the entire history of the swap if is still pending and streams updates in real time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """
        This is a wrapper for channel creation swaps. The daemon only returns the ID, timeout block height and lockup address.
        The Boltz backend takes care of the rest. When an amount of onchain coins that is in the limits is sent to the address
        before the timeout block height, the daemon creates a new lightning invoice, sends it to the Boltz backend which
        will try to pay it and if that is not possible, create a new channel to make the swap succeed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSwap(self, request, context):
        """
        Creates a new swap from onchain to lightning.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChannel(self, request, context):
        """
        Create a new swap from onchain to a new lightning channel. The daemon will only accept the invoice payment if the HTLCs
        is coming trough a new channel channel opened by Boltz.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReverseSwap(self, request, context):
        """
        Creates a new reverse swap from lightning to onchain. If `accept_zero_conf` is set to true in the request, the daemon
        will not wait until the lockup transaction from Boltz is confirmed in a block, but will claim it instantly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWallet(self, request, context):
        """
        Creates a new liquid wallet and returns the mnemonic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportWallet(self, request, context):
        """
        Imports an existing wallet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSubaccount(self, request, context):
        """
        Sets the subaccount of a wallet. Not supported for readonly wallets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubaccounts(self, request, context):
        """
        Returns all subaccounts for a given wallet. Not supported for readonly wallets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallets(self, request, context):
        """
        Returns all available wallets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """
        Returns the current balance and subaccount of a wallet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWalletCredentials(self, request, context):
        """
        Returns the credentials of a wallet. The password will be required if the wallet is encrypted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWallet(self, request, context):
        """
        Removes a wallet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """
        Gracefully stops the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """
        Unlocks the server. This will be required on startup if there are any encrypted wallets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyWalletPassword(self, request, context):
        """
        Check if the password is correct.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeWalletPassword(self, request, context):
        """
        Changes the password for wallet encryption.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoltzServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=boltzrpc__pb2.GetInfoRequest.FromString,
                    response_serializer=boltzrpc__pb2.GetInfoResponse.SerializeToString,
            ),
            'GetServiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceInfo,
                    request_deserializer=boltzrpc__pb2.GetServiceInfoRequest.FromString,
                    response_serializer=boltzrpc__pb2.GetServiceInfoResponse.SerializeToString,
            ),
            'GetSubmarinePair': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubmarinePair,
                    request_deserializer=boltzrpc__pb2.Pair.FromString,
                    response_serializer=boltzrpc__pb2.SubmarinePair.SerializeToString,
            ),
            'GetReversePair': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReversePair,
                    request_deserializer=boltzrpc__pb2.Pair.FromString,
                    response_serializer=boltzrpc__pb2.ReversePair.SerializeToString,
            ),
            'GetPairs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPairs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=boltzrpc__pb2.GetPairsResponse.SerializeToString,
            ),
            'ListSwaps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSwaps,
                    request_deserializer=boltzrpc__pb2.ListSwapsRequest.FromString,
                    response_serializer=boltzrpc__pb2.ListSwapsResponse.SerializeToString,
            ),
            'RefundSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundSwap,
                    request_deserializer=boltzrpc__pb2.RefundSwapRequest.FromString,
                    response_serializer=boltzrpc__pb2.GetSwapInfoResponse.SerializeToString,
            ),
            'GetSwapInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSwapInfo,
                    request_deserializer=boltzrpc__pb2.GetSwapInfoRequest.FromString,
                    response_serializer=boltzrpc__pb2.GetSwapInfoResponse.SerializeToString,
            ),
            'GetSwapInfoStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSwapInfoStream,
                    request_deserializer=boltzrpc__pb2.GetSwapInfoRequest.FromString,
                    response_serializer=boltzrpc__pb2.GetSwapInfoResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=boltzrpc__pb2.DepositRequest.FromString,
                    response_serializer=boltzrpc__pb2.DepositResponse.SerializeToString,
            ),
            'CreateSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSwap,
                    request_deserializer=boltzrpc__pb2.CreateSwapRequest.FromString,
                    response_serializer=boltzrpc__pb2.CreateSwapResponse.SerializeToString,
            ),
            'CreateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChannel,
                    request_deserializer=boltzrpc__pb2.CreateChannelRequest.FromString,
                    response_serializer=boltzrpc__pb2.CreateSwapResponse.SerializeToString,
            ),
            'CreateReverseSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReverseSwap,
                    request_deserializer=boltzrpc__pb2.CreateReverseSwapRequest.FromString,
                    response_serializer=boltzrpc__pb2.CreateReverseSwapResponse.SerializeToString,
            ),
            'CreateWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWallet,
                    request_deserializer=boltzrpc__pb2.CreateWalletRequest.FromString,
                    response_serializer=boltzrpc__pb2.WalletCredentials.SerializeToString,
            ),
            'ImportWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportWallet,
                    request_deserializer=boltzrpc__pb2.ImportWalletRequest.FromString,
                    response_serializer=boltzrpc__pb2.Wallet.SerializeToString,
            ),
            'SetSubaccount': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSubaccount,
                    request_deserializer=boltzrpc__pb2.SetSubaccountRequest.FromString,
                    response_serializer=boltzrpc__pb2.Subaccount.SerializeToString,
            ),
            'GetSubaccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubaccounts,
                    request_deserializer=boltzrpc__pb2.WalletInfo.FromString,
                    response_serializer=boltzrpc__pb2.GetSubaccountsResponse.SerializeToString,
            ),
            'GetWallets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallets,
                    request_deserializer=boltzrpc__pb2.GetWalletsRequest.FromString,
                    response_serializer=boltzrpc__pb2.Wallets.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=boltzrpc__pb2.GetWalletRequest.FromString,
                    response_serializer=boltzrpc__pb2.Wallet.SerializeToString,
            ),
            'GetWalletCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWalletCredentials,
                    request_deserializer=boltzrpc__pb2.GetWalletCredentialsRequest.FromString,
                    response_serializer=boltzrpc__pb2.WalletCredentials.SerializeToString,
            ),
            'RemoveWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWallet,
                    request_deserializer=boltzrpc__pb2.RemoveWalletRequest.FromString,
                    response_serializer=boltzrpc__pb2.RemoveWalletResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=boltzrpc__pb2.UnlockRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'VerifyWalletPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyWalletPassword,
                    request_deserializer=boltzrpc__pb2.VerifyWalletPasswordRequest.FromString,
                    response_serializer=boltzrpc__pb2.VerifyWalletPasswordResponse.SerializeToString,
            ),
            'ChangeWalletPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeWalletPassword,
                    request_deserializer=boltzrpc__pb2.ChangeWalletPasswordRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boltzrpc.Boltz', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Boltz(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetInfo',
            boltzrpc__pb2.GetInfoRequest.SerializeToString,
            boltzrpc__pb2.GetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetServiceInfo',
            boltzrpc__pb2.GetServiceInfoRequest.SerializeToString,
            boltzrpc__pb2.GetServiceInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubmarinePair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetSubmarinePair',
            boltzrpc__pb2.Pair.SerializeToString,
            boltzrpc__pb2.SubmarinePair.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReversePair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetReversePair',
            boltzrpc__pb2.Pair.SerializeToString,
            boltzrpc__pb2.ReversePair.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPairs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetPairs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            boltzrpc__pb2.GetPairsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSwaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/ListSwaps',
            boltzrpc__pb2.ListSwapsRequest.SerializeToString,
            boltzrpc__pb2.ListSwapsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefundSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/RefundSwap',
            boltzrpc__pb2.RefundSwapRequest.SerializeToString,
            boltzrpc__pb2.GetSwapInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSwapInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetSwapInfo',
            boltzrpc__pb2.GetSwapInfoRequest.SerializeToString,
            boltzrpc__pb2.GetSwapInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSwapInfoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/boltzrpc.Boltz/GetSwapInfoStream',
            boltzrpc__pb2.GetSwapInfoRequest.SerializeToString,
            boltzrpc__pb2.GetSwapInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/Deposit',
            boltzrpc__pb2.DepositRequest.SerializeToString,
            boltzrpc__pb2.DepositResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/CreateSwap',
            boltzrpc__pb2.CreateSwapRequest.SerializeToString,
            boltzrpc__pb2.CreateSwapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/CreateChannel',
            boltzrpc__pb2.CreateChannelRequest.SerializeToString,
            boltzrpc__pb2.CreateSwapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReverseSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/CreateReverseSwap',
            boltzrpc__pb2.CreateReverseSwapRequest.SerializeToString,
            boltzrpc__pb2.CreateReverseSwapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/CreateWallet',
            boltzrpc__pb2.CreateWalletRequest.SerializeToString,
            boltzrpc__pb2.WalletCredentials.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/ImportWallet',
            boltzrpc__pb2.ImportWalletRequest.SerializeToString,
            boltzrpc__pb2.Wallet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSubaccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/SetSubaccount',
            boltzrpc__pb2.SetSubaccountRequest.SerializeToString,
            boltzrpc__pb2.Subaccount.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubaccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetSubaccounts',
            boltzrpc__pb2.WalletInfo.SerializeToString,
            boltzrpc__pb2.GetSubaccountsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWallets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetWallets',
            boltzrpc__pb2.GetWalletsRequest.SerializeToString,
            boltzrpc__pb2.Wallets.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetWallet',
            boltzrpc__pb2.GetWalletRequest.SerializeToString,
            boltzrpc__pb2.Wallet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWalletCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/GetWalletCredentials',
            boltzrpc__pb2.GetWalletCredentialsRequest.SerializeToString,
            boltzrpc__pb2.WalletCredentials.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/RemoveWallet',
            boltzrpc__pb2.RemoveWalletRequest.SerializeToString,
            boltzrpc__pb2.RemoveWalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/Stop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/Unlock',
            boltzrpc__pb2.UnlockRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyWalletPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/VerifyWalletPassword',
            boltzrpc__pb2.VerifyWalletPasswordRequest.SerializeToString,
            boltzrpc__pb2.VerifyWalletPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeWalletPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boltzrpc.Boltz/ChangeWalletPassword',
            boltzrpc__pb2.ChangeWalletPasswordRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
