action_id: trunk-upgrade-available
date: 2024-02-13 19:46:33
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1707853593
full_timestamp:
  nanos: 437595000
  seconds: 1707853593
trunk_version: 1.19.0
