from .models import (
    CreateInvoiceRequest,
    CreateInvoiceResponse,
    EmptyRequest,
    KvGetRequest,
    KvGetResponse,
    KvListRequest,
    KvListResponse,
    KvSetRequest,
    KvSetResponse,
    LogRequest,
    LogResponse,
    NowResponse,
    RandomIdRequest,
    RandomIdResponse,
    WatchPaymentRequest,
    WatchPaymentResponse,
)
from .registry import CapabilityDefinition, CapabilityRegistry


def get_extension_capability_registry() -> CapabilityRegistry:
    registry = CapabilityRegistry()

    for capability in [
        CapabilityDefinition(
            id="storage.get",
            namespace="storage",
            name="Get storage value",
            host_name="kv_get",
            sdk_name="get",
            description="Read one value from the extension storage namespace.",
            request_model=KvGetRequest,
            response_model=KvGetResponse,
            required_permission="ext.storage.read_write",
            public_context=True,
        ),
        CapabilityDefinition(
            id="storage.set",
            namespace="storage",
            name="Set storage value",
            host_name="kv_set",
            sdk_name="set",
            description="Write one value to the extension storage namespace.",
            request_model=KvSetRequest,
            response_model=KvSetResponse,
            required_permission="ext.storage.read_write",
        ),
        CapabilityDefinition(
            id="storage.list",
            namespace="storage",
            name="List storage keys",
            host_name="kv_list",
            sdk_name="list",
            description="List keys under a prefix in the extension storage namespace.",
            request_model=KvListRequest,
            response_model=KvListResponse,
            required_permission="ext.storage.read_write",
            public_context=True,
        ),
        CapabilityDefinition(
            id="wallet.create_invoice",
            namespace="wallet",
            name="Create invoice",
            host_name="create_invoice",
            sdk_name="createInvoice",
            description="Create an incoming Lightning invoice for an allowed wallet.",
            request_model=CreateInvoiceRequest,
            response_model=CreateInvoiceResponse,
            required_permission="wallet.create_invoice",
            public_context=True,
        ),
        CapabilityDefinition(
            id="payments.watch",
            namespace="payments",
            name="Watch payment",
            host_name="watch_payment",
            sdk_name="watch",
            description="Subscribe the extension to a payment state callback.",
            request_model=WatchPaymentRequest,
            response_model=WatchPaymentResponse,
            required_permission="payments.watch",
        ),
        CapabilityDefinition(
            id="system.random_id",
            namespace="system",
            name="Random ID",
            host_name="random_id",
            sdk_name="id",
            description="Create a random extension-local identifier.",
            request_model=RandomIdRequest,
            response_model=RandomIdResponse,
            public_context=True,
        ),
        CapabilityDefinition(
            id="system.now",
            namespace="system",
            name="Current timestamp",
            host_name="now",
            sdk_name="now",
            description="Return the current Unix timestamp.",
            request_model=EmptyRequest,
            response_model=NowResponse,
            public_context=True,
        ),
        CapabilityDefinition(
            id="system.log",
            namespace="system",
            name="Log message",
            host_name="log",
            sdk_name="log",
            description="Write a bounded message to the extension log.",
            request_model=LogRequest,
            response_model=LogResponse,
            public_context=True,
        ),
    ]:
        registry.register(capability)

    return registry
