name: make

on:
  workflow_call:
    inputs:
      make:
        description: "make command that is run"
        required: true
        type: string
      python-version:
        description: "python versions array"
        required: true
        type: array
        default: ["3.9", "3.10"]
      npm:
        description: "use npm install"
        default: false
        type: boolean

jobs:
  make:
    name: ${{ inputs.make }} (${{ matrix.python-version }})
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]
        python-version: ${{ inputs.python-version }}
        node-version: ["18.x"]
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          python-version: ${{ matrix.python-version }}
          node-version: ${{ matrix.node-version }}
          npm: ${{ inputs.npm }}
      - run: make ${{ inputs.make }}
