name: make

on:
  workflow_call:
    inputs:
      make:
        description: "make command that is run"
        required: true
        type: string
      npm:
        description: "use npm install"
        default: false
        type: boolean
      python-version:
        description: "python version"
        type: string
        default: "3.10"

jobs:
  make:
    name: ${{ inputs.make }} (${{ inputs.python-version }})
    strategy:
      matrix:
        os-version: ["ubuntu-24.04"]
        node-version: ["18.x"]
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: lnbits/lnbits/.github/actions/prepare@dev
        with:
          python-version: ${{ inputs.python-version }}
          node-version: ${{ matrix.node-version }}
          npm: ${{ inputs.npm }}
      - run: make ${{ inputs.make }}
