name: LNbits CI / nix

# - run   : on main, dev, nix and cachix branches when relevant files change
# - cache : on main, dev and cachix branches when relevant files change

on:
  push:
    branches:
      - main
      - dev
      - nix
      - cachix
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'lnbits/**'
      - 'nix/**'
      - '.github/workflows/nix.yml'
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'lnbits/**'
      - 'nix/**'
      - '.github/workflows/nix.yml'

jobs:
  nix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: cachix/cachix-action@v15
        with:
          name: lnbits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build package
        run: nix build -L
      - name: Smoke test native libraries
        run: |
          ./result/bin/python -c \
            'from coincurve import PrivateKey; from wasmtime import Engine; PrivateKey(); Engine()'
      - name: Check NixOS module
        run: nix build -L .#checks.x86_64-linux.vmTest
      - run: cachix push lnbits ./result
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/cachix'
