name: release-rc

on:
  push:
    tags:
      - "*-rc[0-9]+"

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Create github pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" --prerelease --generate-notes --draft

  uploadurl:
    needs: [ release ]
    runs-on: ubuntu-24.04
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - id: get_upload_url
        name: get upload url of github release
        env:
          github_token: ${{ secrets.github_token }}
          tag: ${{ github.ref_name }}
        run: |
          upload_url=$(gh release view "$tag" --json uploadurl -q ".uploadurl")
          echo "upload_url=$upload_url" >> "$github_output"

  docker:
    if: github.repository == 'lnbits/lnbits'
    uses: ./.github/workflows/docker.yml
    with:
      tag: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  pypi:
    if: github.repository == 'lnbits/lnbits'
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies for building secp256k1
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake libtool libffi-dev libgmp-dev
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.15
        with:
          pypi_token: ${{ secrets.PYPI_API_KEY }}

  appimage:
    needs: [ uploadurl ]
    uses: ./.github/workflows/appimage.yml
    with:
      tag_name: ${{ github.ref_name }}
      upload_url: ${{ needs.uploadurl.outputs.upload_url }}
